apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-storage-pvc
  namespace: orthanc-santiago
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orthanc-db-pvc
  namespace: orthanc-santiago
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-pvc
  namespace: orthanc-santiago
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
