apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc
  namespace: orthanc-santiago
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orthanc
  template:
    metadata:
      labels:
        app: orthanc
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z orthanc-db 5432; do echo waiting for orthanc-db; sleep 3; done']
      containers:
      - name: orthanc
        image: orthancteam/orthanc:24.11.0
        ports:
        - containerPort: 8042
          name: http
        - containerPort: 4242
          name: dicom
        env:
        - name: STONE_WEB_VIEWER_PLUGIN_ENABLEDi
          valueFrom:
            configMapKeyRef:
              name: orthanc-config
              key: STONE_WEB_VIEWER_PLUGIN_ENABLED
        - name: DICOM_WEB_PLUGIN_ENABLED
          valueFrom:
            configMapKeyRef:
              name: orthanc-config
              key: DICOM_WEB_PLUGIN_ENABLED
        - name: STL_PLUGIN_ENABLED
          valueFrom:
            configMapKeyRef:
              name: orthanc-config
              key: STL_PLUGIN_ENABLED
        - name: VERBOSE_ENABLED
          valueFrom:
            configMapKeyRef:
              name: orthanc-config
              key: VERBOSE_ENABLED
        - name: ORTHANC__POSTGRESQL__HOST
          value: "orthanc-db"
        - name: ORTHANC__POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: orthanc-secrets
              key: DB_ORTHANC_PASSWORD
        - name: ORTHANC__POSTGRESQL__TRANSACTION_MODE
          value: "ReadCommitted"
        - name: SVC_INTERNAL_USER
          valueFrom:
            secretKeyRef:
              name: orthanc-secrets
              key: SVC_INTERNAL_USER
        - name: SVC_INTERNAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orthanc-secrets
              key: SVC_INTERNAL_PASSWORD
        - name: PUBLIC_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: orthanc-config
              key: PUBLIC_DOMAIN
        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: orthanc-config
              key: KEYCLOAK_REALM
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: orthanc-config
              key: KEYCLOAK_CLIENT_ID
        - name: ORTHANC_JSON
          value: >-
            {
              "Name": "Orthanc Production",
              "BehindReverseProxy": true,
              "HttpServerPrefix": "/orthanc",
              "OrthancExplorer2": {
                "IsDefaultUI": true,
                "UiOptions": {
                  "EnableShares": true,
                  "EnableOpenInOhifViewer3": true,
                  "OhifViewer3PublicRoot": "http://tfm-sch.imaging.i3m.upv.es/ohif/"
                },
                "Keycloak": {
                  "Enable": true,
                  "Url": "http://tfm-sch.imaging.i3m.upv.es/keycloak/",
                  "Realm": "orthanc",
                  "ClientId": "orthanc"
                }
              },
              "AuthenticationEnabled": false,
              "Authorization": {
                "WebServiceRootUrl": "http://orthanc-auth-service:8000/",
                "WebServiceUsername": "$(SVC_INTERNAL_USER)",
                "WebServicePassword": "$(SVC_INTERNAL_PASSWORD)",
                "StandardConfigurations": ["osimis-web-viewer", "stone-webviewer", "orthanc-explorer-2", "ohif", "stl"],
                "TokenHttpHeaders": ["api-key"],
                "CheckedLevel": "studies"
              }
            }
        volumeMounts:
        - name: storage
          mountPath: /var/lib/orthanc/db
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: orthanc-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: orthanc-service
  namespace: orthanc-santiago
spec:
  type: ClusterIP
  selector:
    app: orthanc
  ports:
  - name: http
    port: 8042
    targetPort: 8042
  - name: dicom
    port: 4242
    targetPort: 4242
